version: '3.8'
services:
  logservice:
    build:
        # dockerfile: ./Dockerfile
        context: ../..
    depends_on:
      - registryservice
    command: ./log_bin
    # profiles:
    #   - all
    environment:
      - LOG_SERVICE_PORT=4000
      - REGISTRY_SERVICE_HOST=registryservice
      - SERVICE_HOSTNAME=logservice
    volumes:
      - ../../dist/app.log:/app/app.log
    ports:
      - "4000" 
  gradingservice:
    build:
        # dockerfile: ./Dockerfile
        context: ../..
    depends_on:
      - registryservice
      - logservice
    command: ./grading_bin
    # profiles:
    #   - all
    environment:
      - GRADING_SERVICE_PORT=6000 # so we have unique urls for the service registry
      - REGISTRY_SERVICE_HOST=registryservice
      - SERVICE_HOSTNAME=gradingservice
    ports:
      - "6000" 
  registryservice:
    build:
        # dockerfile: ./Dockerfile
        context: ../..
    command: ./registry_bin
    restart: always
    # profiles:
    #   - all
    ports:
      - "3000" 
    environment:
      REGISTRY_SERVICE_PORT: 3000
      REGISTRY_SERVICE_HOST: registryservice

    